# Maths Ordinary Differential Equations

## Numerical Methods for ODEs

* In this Python workbook we will implement several methods for solving ordinary differential equations using numerical methods.

* The methods we investigate include Euler's method, the Euler-Heun method and the Euler method for a system of ODEs.

* Each of these methods will be covered in lectures also.

* The purpose of this Python workbook is to compliment these lectures and implement the methods as they normally are in research and industry.

## Importing Libraries and Functions

In [1]:
import numpy as np
import matplotlib.pyplot as plt

__import__ is a function that instructs Python to import the numpy library of functions and give it the abbreviated name np.

__Numpy__ is a library of functions, and contains several functions we are familiar with from lectures and from our scientific calculators. 

__Maptplotlib.pyplot__ is a library of Python functions we will use for plotting solutions of ODEs and any other functions we may want to visualise.

## Code cells & Markdown cells

* In these Python work books, there are two types of cells we will use.

#### Code Cells

* The first of these are __code__ cells, where we type and run actual code. To run a code cell press __Shift+Enter__ together.

#### Markdown Cells

* The other type of cell is called a __markdown__ cell. The current cell is an example of a markdown cell. It is useful for presenting text when we want to explain code or equations. The edit a markdown cell double click it. Then press __Shit+Enter__ to render it in regular text.

# Euler's Method



## Euler's method in theory

* Euler's method is used to solve ordinary differential equations of the form
\\[\frac{dy}{dx}=f(x,y),\\]
where $f(x,y)$ is some (possilby nonlinear) function of $x$ and $y$.


* The basic idea behind Euler's method is the derivative is formally defined as
\\[\frac{dy}{dx}=\lim_{h\to0}\frac{y(x+h)-y(x)}{h},\\]
and so for a __small__ but finite value of $h$ we may make the approximation
\\[\frac{dy}{dx}\approx\frac{y(x+h)-y(x)}{h}.\\]


* This means, if we know $y(x)$ and $\frac{dy}{dx}$ at $x$, then we can _step x forward__ by $h$ to fins $y(x+h)$, using
\\[y(x+h)\approx y(x)+h\frac{dy}{dx}.\\]


* The next part of the idea is using the fact that the ODE allowes us to rewrite $\frac{dy}{dx}$ in terms of $y(x)$ alone, i.e. it is just the right-hand side of the ODE, and so we have
\\[y(x+h)\approx y(x)+hf(x,y(x)).\\]

## Euler's Method - Example 1

* In this section we will go through the steps of creating the Euler method to solve the simple ODE
\\[\frac{dy}{dx}=\frac{y^2}{5},\quad y(1.2)=4.3,\\]
and find its value at $x=1.5$.



* While this ODE is nonlinear it can be solved directly, without numerical methods. However, it is a simple example to develop Python code for Euler's method to solve for $y$.


* The first step is to create a Python function to represent $f(x,y)$. 

In [17]:
def f(y):
    return y**2/5.0

Next we define the __number of steps__ we want to use to estimate $y(1.5)$. We will use 50, however this is easily change in the cell below.

In [57]:
N=501

The __step-size__ is now given by
\\[h=\frac{1.5-1.2}{50}.\\]

In [64]:
h=(1.5-1.2)/N
h

0.0005988023952095809

Now we create a __for loop__ that implements each step of Euler's method 50 times. However, we must first set up the initial condition $y(1.2)=4.3$

In [65]:
x0=1.2
y0=4.3

#### Initialisation

* When using computers to implement these numerical methods, it is usually necessary to initialise the solution y.

* This usually means first setting the solution we seek to be initially zero, i.e. it is our first guess for the soulution.

##### Note: This is not the same as setting the initial condition y(1.2)=4.3. It is the starting point the computer uses to calculate the solution we seek.

In [60]:
x=np.zeros(N+1)
y=np.zeros(N+1)

In [66]:
for i in range (1,N):
    x[0]=x0
    y[0]=y0
    x[i]=x[i-1]+h
    y[i] = y[i-1] + h*f(y[i-1])

In [67]:
y

array([4.3       , 4.30221437, 4.30443102, 4.30664996, 4.30887119,
       4.3110947 , 4.31332052, 4.31554863, 4.31777904, 4.32001176,
       4.32224679, 4.32448414, 4.3267238 , 4.32896578, 4.33121008,
       4.33345672, 4.33570568, 4.33795698, 4.34021061, 4.34246659,
       4.34472492, 4.34698559, 4.34924862, 4.35151401, 4.35378175,
       4.35605186, 4.35832434, 4.36059919, 4.36287641, 4.36515602,
       4.367438  , 4.36972238, 4.37200914, 4.3742983 , 4.37658985,
       4.37888381, 4.38118017, 4.38347894, 4.38578013, 4.38808373,
       4.39038975, 4.3926982 , 4.39500907, 4.39732237, 4.39963812,
       4.4019563 , 4.40427692, 4.4066    , 4.40892552, 4.4112535 ,
       4.41358394, 4.41591684, 4.41825221, 4.42059004, 4.42293036,
       4.42527315, 4.42761842, 4.42996618, 4.43231644, 4.43466918,
       4.43702443, 4.43938217, 4.44174243, 4.44410519, 4.44647047,
       4.44883826, 4.45120858, 4.45358143, 4.4559568 , 4.45833471,
       4.46071516, 4.46309816, 4.46548369, 4.46787178, 4.47026

In [72]:
x;

### The exact solution

* As was noted in the introduction to this example, this ODE has a exact solution, which is given by
\\[y(x)=\frac{21.5}{10.16-4.3x}.\\]


* We create a Python function to represent this solution as follows:

In [69]:
def y_ex(x):
    return 21.5/(10.16-4.3*x)

The exact values of $y$ at each of the values of $x$ above are given by

In [70]:
y_ex(x)

array([4.3       , 4.30221551, 4.30443331, 4.30665339, 4.30887577,
       4.31110044, 4.31332741, 4.31555668, 4.31778825, 4.32002214,
       4.32225834, 4.32449685, 4.32673768, 4.32898084, 4.33122633,
       4.33347414, 4.33572429, 4.33797678, 4.34023161, 4.34248878,
       4.34474831, 4.34701018, 4.34927441, 4.35154101, 4.35380996,
       4.35608129, 4.35835498, 4.36063105, 4.3629095 , 4.36519033,
       4.36747354, 4.36975915, 4.37204715, 4.37433754, 4.37663034,
       4.37892554, 4.38122316, 4.38352318, 4.38582562, 4.38813048,
       4.39043776, 4.39274747, 4.39505961, 4.39737419, 4.39969121,
       4.40201067, 4.40433257, 4.40665693, 4.40898374, 4.41131301,
       4.41364474, 4.41597894, 4.41831561, 4.42065476, 4.42299638,
       4.42534048, 4.42768707, 4.43003615, 4.43238772, 4.4347418 ,
       4.43709837, 4.43945745, 4.44181904, 4.44418314, 4.44654976,
       4.4489189 , 4.45129057, 4.45366477, 4.4560415 , 4.45842077,
       4.46080258, 4.46318694, 4.46557385, 4.46796332, 4.47035

In [74]:
y_ex(x)-y

array([-8.88178420e-16,  1.14092244e-06,  2.28478531e-06,  3.43159649e-06,
        4.58136390e-06,  5.73409547e-06,  6.88979915e-06,  8.04848292e-06,
        9.21015480e-06,  1.03748228e-05,  1.15424950e-05,  1.27131795e-05,
        1.38868843e-05,  1.50636177e-05,  1.62433877e-05,  1.74262025e-05,
        1.86120704e-05,  1.98009995e-05,  2.09929982e-05,  2.21880747e-05,
        2.33862373e-05,  2.45874943e-05,  2.57918541e-05,  2.69993252e-05,
        2.82099158e-05,  2.94236344e-05,  3.06404896e-05,  3.18604897e-05,
        3.30836433e-05,  3.43099589e-05,  3.55394452e-05,  3.67721106e-05,
        3.80079638e-05,  3.92470135e-05,  4.04892683e-05,  4.17347369e-05,
        4.29834281e-05,  4.42353506e-05,  4.54905132e-05,  4.67489247e-05,
        4.80105939e-05,  4.92755296e-05,  5.05437409e-05,  5.18152366e-05,
        5.30900256e-05,  5.43681169e-05,  5.56495196e-05,  5.69342426e-05,
        5.82222950e-05,  5.95136859e-05,  6.08084244e-05,  6.21065196e-05,
        6.34079808e-05,  

* We see that the numerical and exact values are reasonably close, however there are some discrepancies towards the end of the list.


* The reduce these differences we increase the number of steps __N__.


* This has the effect of reducing the step-size __h__, which make the approximation of the derivative above.


* Increase the the number of steps to __N=501__, and compare the numerical and  exact solutions again.