# Maths Ordinary Differential Equations 2020

## Section 3 - Numerical Mehods

### Import the required libraries 

In [1]:
import numpy as np
from numpy import cos, sin, exp, pi

In [2]:
import matplotlib.pyplot as plt

# Euler's Method

* This python workbook is for solvinf differential equations of the form

$$
\frac{dy}{dx} - f(x,y)=0.
$$


* The funtion $f(x,y)$ is a function of both $x$ and $y$, and defpending on its form, it may or may not be possible to separate the variables of the ODE.


* In any case, Euler's method will allow us to solve te ODE numerically.


* The algorithm for Euler's method is 
$$
y_{i+1}=y_{i}+h\cdot f(x_{i},y_{i}).
$$


## Example 1

* Solve the ODE
$$
\frac{dy}{dx}=\frac{x^2+y^2}{10} \quad y(1.4)=2.5
$$
on the interval between $x=1.4$ and $x=1.5$ using 5 steps of Euler's method

### Solution

* We must define the function $f(x,y)=\frac{x^2+y^2}{10}$ as follows

In [3]:
def f(x,y):
    return x+exp(-y)

* The algorithm for Euler's method is implemented in the cell below:

In [4]:
def Euler(f, x0, xn, y0, n):
    x = np.linspace(x0,xn,n+1)
    h=x[1]-x[0]
    y = np.zeros(n+1)
    for i in range(n+1):
        y[0]=y0
        y[i]= y[i-1]+h * f(x[i-1], y[i-1])
        x[i]=x[i-1]+h
    return y

In [5]:
x0=1.4
xn=1.5
y0=2.5
n=5
h=(xn-x0)/n
h,Euler(f,x0,xn,y0,n)

(0.020000000000000018,
 array([2.5       , 2.5320417 , 2.56443163, 2.59717089, 2.63026057,
        2.66370176]))

# The Euler-Heun Method


* The Euler-Heun method (or often just Heun's method) is a more accurate version of Euler's method.



* It is a more complicated procedure, since each step of the algorithim requires us to apply an intermediate step using Euler's algorithm. 

In [8]:
def Heun(f, x0, xn, y0, n):
    x = np.linspace(x0,xn,n+1)
    h=x[1]-x[0]
    y = np.zeros(n+1)
    ey = np.zeros(n+1)
    for i in range(n+1):
        y[0]=y0
        ey[0]=y0
        ey[i]=y[i-1]+h*f(x[i-1],y[i-1])
        y[i]=y[i-1]+0.5*h*(f(x[i-1],y[i-1])+f(x[i],ey[i]))
    return ey,y

In [9]:
x0=1.2
xn=1.28
y0=0.5
n=2
h=(xn-x0)/n
h,Heun(f,x0,xn,y0,n)

(0.040000000000000036,
 (array([0.5       , 0.57226123, 0.64438653]),
  array([0.5       , 0.57221558, 0.64440074])))

# Euler's Method for Matrix Systems

In [ ]:
def F(x,y1,y2):
    return np.array([[x,y1+y2],[y1-y2,x]])

In [ ]:
def EulerMatrix(F, x0, xn, Ya, n):
    x = np.linspace(x0,xn,n+1)
    h=x[1]-x[0]
    Y = np.array([np.zeros(n+1),np.zeros(n+1)])
    for i in range(n+1):
        Y[:,0]=Ya
        Y[:,i]= Y[:,i-1]+h * np.dot(F(x[i-1], Y[0,i-1],Y[1,i-1]),Y[:,i-1])
    return x,Y

In [ ]:
Ya=np.array([3.4,5.7])
Ya

array([3.4, 5.7])

In [ ]:
x0=2
xn=2.1
n=2
EulerMatrix(F,x0,xn,Ya,n)

(array([2.  , 2.05, 2.1 ]),
 array([[ 3.4       ,  6.3335    , 10.57254812],
        [ 5.7       ,  5.879     ,  6.62552629]]))